import type { HexType } from "../../data/boards/types";
import desert from "./desert.svg";
import fields from "./fields.svg";
import fog from "./fog.svg";
import forest from "./forest.svg";
import gold from "./gold.svg";
import hills from "./hills.svg";
import mountains from "./mountains.svg";
import pasture from "./pasture.svg";
import sea from "./sea.svg";
import village from "./village.svg";

/** Terrain artwork, generated by scripts/generate-hex-art.mjs. */
export const HEX_ART: Record<HexType, string> = {
  desert,
  fields,
  fog,
  forest,
  gold,
  hills,
  mountains,
  pasture,
  sea,
  village,
};
