import brick from "./brick.svg";
import cloth from "./cloth.svg";
import coin from "./coin.svg";
import ore from "./ore.svg";
import paper from "./paper.svg";
import wheat from "./wheat.svg";
import wood from "./wood.svg";
import wool from "./wool.svg";

/** Resource and commodity tokens, generated by scripts/generate-hex-art.mjs. */
export const RESOURCE_ICON = { brick, wood, wool, wheat, ore } as const;
export const COMMODITY_ICON = { paper, cloth, coin } as const;
